// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8rmCv1h-nBRKDXsE3ICq8KD__ZuOB9so',
    appId: '1:100913023077:web:eaa8d01a323e8a3f4d9e8c',
    messagingSenderId: '100913023077',
    projectId: 'fiuuassistant',
    authDomain: 'fiuuassistant.firebaseapp.com',
    storageBucket: 'fiuuassistant.firebasestorage.app',
    measurementId: 'G-QF28VJ7200',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf2FbQOtgierTRKV8mpSU4XEMzve-ZcMg',
    appId: '1:100913023077:android:7fd9effbf900170d4d9e8c',
    messagingSenderId: '100913023077',
    projectId: 'fiuuassistant',
    storageBucket: 'fiuuassistant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu0p2tnURQcWDdO1S45I__qXVheUAzzv0',
    appId: '1:100913023077:ios:6841a5baeef990c64d9e8c',
    messagingSenderId: '100913023077',
    projectId: 'fiuuassistant',
    storageBucket: 'fiuuassistant.firebasestorage.app',
    iosBundleId: 'com.example.fiuuassistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu0p2tnURQcWDdO1S45I__qXVheUAzzv0',
    appId: '1:100913023077:ios:6841a5baeef990c64d9e8c',
    messagingSenderId: '100913023077',
    projectId: 'fiuuassistant',
    storageBucket: 'fiuuassistant.firebasestorage.app',
    iosBundleId: 'com.example.fiuuassistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8rmCv1h-nBRKDXsE3ICq8KD__ZuOB9so',
    appId: '1:100913023077:web:fbd0d501941467d74d9e8c',
    messagingSenderId: '100913023077',
    projectId: 'fiuuassistant',
    authDomain: 'fiuuassistant.firebaseapp.com',
    storageBucket: 'fiuuassistant.firebasestorage.app',
    measurementId: 'G-TH701J3W47',
  );
}
